"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _HandSide:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HandSideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HandSide.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RIGHT: _HandSide.ValueType  # 0
    LEFT: _HandSide.ValueType  # 1
    NONE: _HandSide.ValueType  # 2

class HandSide(_HandSide, metaclass=_HandSideEnumTypeWrapper): ...

RIGHT: HandSide.ValueType  # 0
LEFT: HandSide.ValueType  # 1
NONE: HandSide.ValueType  # 2
global___HandSide = HandSide

@typing_extensions.final
class Matrix4x4(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data"]) -> None: ...

global___Matrix4x4 = Matrix4x4

@typing_extensions.final
class HandFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIDE_FIELD_NUMBER: builtins.int
    POSE_FIELD_NUMBER: builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: builtins.int
    side: global___HandSide.ValueType
    @property
    def pose(self) -> global___Matrix4x4: ...
    timestamp_ms: builtins.int
    def __init__(
        self,
        *,
        side: global___HandSide.ValueType = ...,
        pose: global___Matrix4x4 | None = ...,
        timestamp_ms: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pose", b"pose"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pose", b"pose", "side", b"side", "timestamp_ms", b"timestamp_ms"]) -> None: ...

global___HandFrame = HandFrame

@typing_extensions.final
class CameraFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JPEG_DATA_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: builtins.int
    jpeg_data: builtins.bytes
    width: builtins.int
    height: builtins.int
    timestamp_ms: builtins.int
    def __init__(
        self,
        *,
        jpeg_data: builtins.bytes = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        timestamp_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["height", b"height", "jpeg_data", b"jpeg_data", "timestamp_ms", b"timestamp_ms", "width", b"width"]) -> None: ...

global___CameraFrame = CameraFrame

@typing_extensions.final
class FrameResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___FrameResponse = FrameResponse

@typing_extensions.final
class AllFrames(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAMERA_FRAME_FIELD_NUMBER: builtins.int
    R_HAND_FRAME_FIELD_NUMBER: builtins.int
    L_HAND_FRAME_FIELD_NUMBER: builtins.int
    @property
    def camera_frame(self) -> global___CameraFrame: ...
    @property
    def r_hand_frame(self) -> global___HandFrame: ...
    @property
    def l_hand_frame(self) -> global___HandFrame: ...
    def __init__(
        self,
        *,
        camera_frame: global___CameraFrame | None = ...,
        r_hand_frame: global___HandFrame | None = ...,
        l_hand_frame: global___HandFrame | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["camera_frame", b"camera_frame", "l_hand_frame", b"l_hand_frame", "r_hand_frame", b"r_hand_frame"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["camera_frame", b"camera_frame", "l_hand_frame", b"l_hand_frame", "r_hand_frame", b"r_hand_frame"]) -> None: ...

global___AllFrames = AllFrames
