# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frames.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66rames.proto\x12\x08grabette\"\x19\n\tMatrix4x4\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"f\n\tHandFrame\x12 \n\x04side\x18\x01 \x01(\x0e\x32\x12.grabette.HandSide\x12!\n\x04pose\x18\x02 \x01(\x0b\x32\x13.grabette.Matrix4x4\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\"U\n\x0b\x43\x61meraFrame\x12\x11\n\tjpeg_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\"1\n\rFrameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x8e\x01\n\tAllFrames\x12+\n\x0c\x63\x61mera_frame\x18\x01 \x01(\x0b\x32\x15.grabette.CameraFrame\x12)\n\x0cr_hand_frame\x18\x02 \x01(\x0b\x32\x13.grabette.HandFrame\x12)\n\x0cl_hand_frame\x18\x03 \x01(\x0b\x32\x13.grabette.HandFrame*)\n\x08HandSide\x12\t\n\x05RIGHT\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\x08\n\x04NONE\x10\x02\x32\x9f\x03\n\x0fGrabetteService\x12\x41\n\x0fSendCameraFrame\x12\x15.grabette.CameraFrame\x1a\x17.grabette.FrameResponse\x12\x45\n\x11StreamCameraFrame\x12\x15.grabette.CameraFrame\x1a\x17.grabette.FrameResponse(\x01\x12=\n\rSendHandFrame\x12\x13.grabette.HandFrame\x1a\x17.grabette.FrameResponse\x12\x41\n\x0fStreamHandFrame\x12\x13.grabette.HandFrame\x1a\x17.grabette.FrameResponse(\x01\x12=\n\rSendAllFrames\x12\x13.grabette.AllFrames\x1a\x17.grabette.FrameResponse\x12\x41\n\x0fStreamAllFrames\x12\x13.grabette.AllFrames\x1a\x17.grabette.FrameResponse(\x01\x42\x0f\xaa\x02\x0cGrabette.APIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frames_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014Grabette.API'
  _globals['_HANDSIDE']._serialized_start=440
  _globals['_HANDSIDE']._serialized_end=481
  _globals['_MATRIX4X4']._serialized_start=26
  _globals['_MATRIX4X4']._serialized_end=51
  _globals['_HANDFRAME']._serialized_start=53
  _globals['_HANDFRAME']._serialized_end=155
  _globals['_CAMERAFRAME']._serialized_start=157
  _globals['_CAMERAFRAME']._serialized_end=242
  _globals['_FRAMERESPONSE']._serialized_start=244
  _globals['_FRAMERESPONSE']._serialized_end=293
  _globals['_ALLFRAMES']._serialized_start=296
  _globals['_ALLFRAMES']._serialized_end=438
  _globals['_GRABETTESERVICE']._serialized_start=484
  _globals['_GRABETTESERVICE']._serialized_end=899
# @@protoc_insertion_point(module_scope)
