# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import frames_pb2 as frames__pb2


class GrabetteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCameraFrame = channel.unary_unary(
                '/grabette.GrabetteService/SendCameraFrame',
                request_serializer=frames__pb2.CameraFrame.SerializeToString,
                response_deserializer=frames__pb2.FrameResponse.FromString,
                )
        self.StreamCameraFrame = channel.stream_unary(
                '/grabette.GrabetteService/StreamCameraFrame',
                request_serializer=frames__pb2.CameraFrame.SerializeToString,
                response_deserializer=frames__pb2.FrameResponse.FromString,
                )
        self.SendHandFrame = channel.unary_unary(
                '/grabette.GrabetteService/SendHandFrame',
                request_serializer=frames__pb2.HandFrame.SerializeToString,
                response_deserializer=frames__pb2.FrameResponse.FromString,
                )
        self.StreamHandFrame = channel.stream_unary(
                '/grabette.GrabetteService/StreamHandFrame',
                request_serializer=frames__pb2.HandFrame.SerializeToString,
                response_deserializer=frames__pb2.FrameResponse.FromString,
                )
        self.SendAllFrames = channel.unary_unary(
                '/grabette.GrabetteService/SendAllFrames',
                request_serializer=frames__pb2.AllFrames.SerializeToString,
                response_deserializer=frames__pb2.FrameResponse.FromString,
                )
        self.StreamAllFrames = channel.stream_unary(
                '/grabette.GrabetteService/StreamAllFrames',
                request_serializer=frames__pb2.AllFrames.SerializeToString,
                response_deserializer=frames__pb2.FrameResponse.FromString,
                )


class GrabetteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCameraFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCameraFrame(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHandFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHandFrame(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAllFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAllFrames(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrabetteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCameraFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCameraFrame,
                    request_deserializer=frames__pb2.CameraFrame.FromString,
                    response_serializer=frames__pb2.FrameResponse.SerializeToString,
            ),
            'StreamCameraFrame': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamCameraFrame,
                    request_deserializer=frames__pb2.CameraFrame.FromString,
                    response_serializer=frames__pb2.FrameResponse.SerializeToString,
            ),
            'SendHandFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHandFrame,
                    request_deserializer=frames__pb2.HandFrame.FromString,
                    response_serializer=frames__pb2.FrameResponse.SerializeToString,
            ),
            'StreamHandFrame': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamHandFrame,
                    request_deserializer=frames__pb2.HandFrame.FromString,
                    response_serializer=frames__pb2.FrameResponse.SerializeToString,
            ),
            'SendAllFrames': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAllFrames,
                    request_deserializer=frames__pb2.AllFrames.FromString,
                    response_serializer=frames__pb2.FrameResponse.SerializeToString,
            ),
            'StreamAllFrames': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAllFrames,
                    request_deserializer=frames__pb2.AllFrames.FromString,
                    response_serializer=frames__pb2.FrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grabette.GrabetteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrabetteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCameraFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grabette.GrabetteService/SendCameraFrame',
            frames__pb2.CameraFrame.SerializeToString,
            frames__pb2.FrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamCameraFrame(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/grabette.GrabetteService/StreamCameraFrame',
            frames__pb2.CameraFrame.SerializeToString,
            frames__pb2.FrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendHandFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grabette.GrabetteService/SendHandFrame',
            frames__pb2.HandFrame.SerializeToString,
            frames__pb2.FrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamHandFrame(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/grabette.GrabetteService/StreamHandFrame',
            frames__pb2.HandFrame.SerializeToString,
            frames__pb2.FrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendAllFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grabette.GrabetteService/SendAllFrames',
            frames__pb2.AllFrames.SerializeToString,
            frames__pb2.FrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamAllFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/grabette.GrabetteService/StreamAllFrames',
            frames__pb2.AllFrames.SerializeToString,
            frames__pb2.FrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
