"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import frames_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class GrabetteServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    SendCameraFrame: grpc.UnaryUnaryMultiCallable[
        frames_pb2.CameraFrame,
        frames_pb2.FrameResponse,
    ]
    StreamCameraFrame: grpc.StreamUnaryMultiCallable[
        frames_pb2.CameraFrame,
        frames_pb2.FrameResponse,
    ]
    SendHandFrame: grpc.UnaryUnaryMultiCallable[
        frames_pb2.HandFrame,
        frames_pb2.FrameResponse,
    ]
    StreamHandFrame: grpc.StreamUnaryMultiCallable[
        frames_pb2.HandFrame,
        frames_pb2.FrameResponse,
    ]
    SendAllFrames: grpc.UnaryUnaryMultiCallable[
        frames_pb2.AllFrames,
        frames_pb2.FrameResponse,
    ]
    StreamAllFrames: grpc.StreamUnaryMultiCallable[
        frames_pb2.AllFrames,
        frames_pb2.FrameResponse,
    ]

class GrabetteServiceAsyncStub:
    SendCameraFrame: grpc.aio.UnaryUnaryMultiCallable[
        frames_pb2.CameraFrame,
        frames_pb2.FrameResponse,
    ]
    StreamCameraFrame: grpc.aio.StreamUnaryMultiCallable[
        frames_pb2.CameraFrame,
        frames_pb2.FrameResponse,
    ]
    SendHandFrame: grpc.aio.UnaryUnaryMultiCallable[
        frames_pb2.HandFrame,
        frames_pb2.FrameResponse,
    ]
    StreamHandFrame: grpc.aio.StreamUnaryMultiCallable[
        frames_pb2.HandFrame,
        frames_pb2.FrameResponse,
    ]
    SendAllFrames: grpc.aio.UnaryUnaryMultiCallable[
        frames_pb2.AllFrames,
        frames_pb2.FrameResponse,
    ]
    StreamAllFrames: grpc.aio.StreamUnaryMultiCallable[
        frames_pb2.AllFrames,
        frames_pb2.FrameResponse,
    ]

class GrabetteServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def SendCameraFrame(
        self,
        request: frames_pb2.CameraFrame,
        context: _ServicerContext,
    ) -> typing.Union[frames_pb2.FrameResponse, collections.abc.Awaitable[frames_pb2.FrameResponse]]: ...
    @abc.abstractmethod
    def StreamCameraFrame(
        self,
        request_iterator: _MaybeAsyncIterator[frames_pb2.CameraFrame],
        context: _ServicerContext,
    ) -> typing.Union[frames_pb2.FrameResponse, collections.abc.Awaitable[frames_pb2.FrameResponse]]: ...
    @abc.abstractmethod
    def SendHandFrame(
        self,
        request: frames_pb2.HandFrame,
        context: _ServicerContext,
    ) -> typing.Union[frames_pb2.FrameResponse, collections.abc.Awaitable[frames_pb2.FrameResponse]]: ...
    @abc.abstractmethod
    def StreamHandFrame(
        self,
        request_iterator: _MaybeAsyncIterator[frames_pb2.HandFrame],
        context: _ServicerContext,
    ) -> typing.Union[frames_pb2.FrameResponse, collections.abc.Awaitable[frames_pb2.FrameResponse]]: ...
    @abc.abstractmethod
    def SendAllFrames(
        self,
        request: frames_pb2.AllFrames,
        context: _ServicerContext,
    ) -> typing.Union[frames_pb2.FrameResponse, collections.abc.Awaitable[frames_pb2.FrameResponse]]: ...
    @abc.abstractmethod
    def StreamAllFrames(
        self,
        request_iterator: _MaybeAsyncIterator[frames_pb2.AllFrames],
        context: _ServicerContext,
    ) -> typing.Union[frames_pb2.FrameResponse, collections.abc.Awaitable[frames_pb2.FrameResponse]]: ...

def add_GrabetteServiceServicer_to_server(servicer: GrabetteServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
